### PR TITLE
Add Jammy to Pythonic dependencies

### PR DESCRIPTION
**Pull request by joshuatcasey**
Fix `pip` and add Jammy to `python`, `pipenv`, and `poetry`.

### CODE REVIEW

**Comment by sophiewigmore** [comment]
Is there any context about the version constraints you've chosen? / Are Python maintainers aligned with these version constraints?

**Comment by joshuatcasey** [comment]
I chose the latest version available in each of the buildpacks, since that the integration tests should use. I don't want to indicate version compatibility unless we've actually run integration tests or done some kind of analysis.

**Comment by sophiewigmore** [comment]
@joshuatcasey thinking about this more, I believe the version the constraints introduced here were a way to only mark Jammy as compatible with specific version lines like in https://github.com/paketo-buildpacks/dep-server/pull/179.

I don't really think the constraints are necessary here, because the same thing versions will be affected either way. If you'd like to keep them that's fine though

**Review by sophiewigmore — APPROVED** [review]

**Comment by joshuatcasey** [comment]
I'm comfortable having some constraints and then relaxing the constraints later if we need to.

I can't merge this PR though, could a @paketo-buildpacks/dependencies team member do so?

**Pull request merged**
