### PR TITLE
Add a new dependency management code inputs validator

### PR DESCRIPTION
**Pull request by sophiewigmore**
With the new dependency management work we are rolling out in https://github.com/paketo-buildpacks/rfcs/issues/236, a team member had the idea to create a small validator for the buildpack-specific code (Phase-1 related changes) for maintainers to use when reviewing dependency management PRs. The goal was for the validator to double check that the retrieval, test, and compilation code provided as a part of `Phase 1 - Adopting Federated Model` in that issue had the right inputs/outputs as laid out in the RFC

### CODE REVIEW

**Comment by sophiewigmore** [comment]
cc @joshuatcasey @TisVictress if you are interested

**Comment by sophiewigmore** [comment]
Fixing a couple things before merge. @TisVictress let meknow any issues besides the name of the compiled dependency

**Review by brayanhenao — APPROVED** [review]
LGTM. Waiting for @TisVictress review to merge it

**Comment by sophiewigmore** [comment]
Thanks Brayan :)

**Review by TisVictress — APPROVED** [review]

**Pull request merged**
