### PR TITLE
Remove Python (CPython) compilation

### PR DESCRIPTION
**Pull request by joshuatcasey**
Now that the `cpython` buildpack [uses the new dependency workflow](https://github.com/paketo-buildpacks/cpython/issues/393) to compile `cpython`, we can remove `cpython` compilation from `dep-server`.

I chose to leave the `cpython` code references alone, for several reasons:
1. Historical: "Just in case" we need to reference them again, it's easiest just to come and look without worrying about commit history.
2. Convenience: I wasn't sure what I could change without side effects in other compilation processes. Besides, it looked hard to do.

Also see #232

### CODE REVIEW

**Comment by joshuatcasey** [comment]
BLOCKED on #235

**Comment by brayanhenao** [comment]
@joshuatcasey Could you rebase the PR with main?

**Comment by joshuatcasey** [comment]
Unblocked now that #235  is merged

**Comment by joshuatcasey** [comment]
@brayanhenao done

**Review by brayanhenao — APPROVED** [review]

**Pull request merged**
